### ISSUE TITLE
Error "Could not connect PeerConnection after timeout"

### ISSUE THREAD

**Issue by CaosFR** [livekit/livekit#1060]
Hi,

Since last update I got a error for every client outside my LAN who try to connect to a room a/v of my livekit server (self-host) : "Could not connect PeerConnection after timeout". If I try inside my LAN it's ok (192.168.x.x).
I have try to disable, my UFW, my fail2ban and the firewall of my Internet Box, activate the DMZ. I have make a new fresh install of livekit. I have other service (https) without any problems to connect. All service are NAT forwardings.

Repoduce the error : 
Go to : https://example.livekit.io/ or https://livekit.io/connection-test
LiveKit URL : https://my.hombrew.dns/
Token : Generate with "docker run --rm -v$PWD:/output livekit/generate --local"

=> Ok for me (LAN), error for client (INTERNET).

For information : Old post for the configuration with docker "https://github.com/livekit/livekit/issues/687"

Thanks for any help, I become mad..

Configuration : 
```
cat docker-compose.yaml
version: '3'

services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml --node-ip xxx
    container_name: livekit
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "7881:7881"
      - "7882:7882/udp"
    networks:
      - proxy
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.livekit.entrypoints=web,websecure"
      - "traefik.http.routers.livekit.rule=Host(`xxx.xxx.xxx`)"
      - "traefik.http.routers.livekit.service=livekit"
      - "traefik.http.routers.livekit.tls=true"
      - "traefik.http.routers.livekit.tls.domains[0].main=xxx.xxx.xxx"
      - "traefik.http.routers.livekit.tls.domains[0].sans=*-*.xxx.xxx"
      - "traefik.http.services.livekit.loadbalancer.server.port=7880"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

```
cat livekit.yaml
port: 7880
rtc:
    udp_port: 7882
    tcp_port: 7881
    use_external_ip: false
keys:
    XXX: XXX
logging:
    json: false
    level: info
```

```
sudo ufw status
Status: active
To                         Action      From
--                         ------      ----
XXX
7881/tcp                   ALLOW       Anywhere
7882/udp                   ALLOW       Anywhere
XXX
7881/tcp (v6)              ALLOW       Anywhere (v6)
7882/udp (v6)              ALLOW       Anywhere (v6)
```
NAT :
![Capture](https://user-images.githubusercontent.com/37581932/193129631-0a9e9245-e8a4-4fdc-a7da-c8a6e7adc5c6.PNG)
```
Error from https://livekit.io/connection-test
Connecting to signal connection via WebSocket

Connected to server, version 1.2.3.

Establishing WebRTC connection

Warning: ports need to be open on firewall in order to connect.

Error: could not connect after timeout

SKIPPED: Can connect via TURN

Warning: No TURN servers configured.

Can publish audio

Error: could not connect after timeout

Can publish video

Error: could not connect after timeout

Resuming connection after interruption

Warning: could not connect after timeout

Fail
```
Log : [livekit_log.txt](https://github.com/livekit/livekit/files/9678767/livekit_log.txt)

**Comment by duiniuluantanqin** [comment]
the error  is the same as mine. it is happened at about 12:00 noon yesterday.Have you solved it?

**Comment by davidzhao** [comment]
I believe this is a compatibility issue that we've introduced in 1.2.3. We'll release a new update that reverts this change in the next version. Apologies for the breakage.

**Comment by duiniuluantanqin** [comment]
But I didn't update it, and it works well before yesterday, with version 1.2.1 .

**Comment by CaosFR** [comment]
@duiniuluantanqin No it's not solve, I work on my issue few hours. I have competely remove all protection but without succes.
@davidzhao Thanks, I will waiting and test again.

**Comment by CaosFR** [comment]
@duiniuluantanqin No it's not solve, I work on my issue few hours. I have competely remove all protection but without succes.
@davidzhao Thanks, I will waiting and test again but I have downgrade to 1.21 and it's not solve.

**Comment by CaosFR** [comment]
@davidzhao Thanks, I will waiting and test again. I have test with the v1.2.1 but I get the same error. I have downgrade my traefik to v2.8.5 beceause the latest version seem breakage livekit.

My config :

$ docker images
[...]
traefik                        v2.8.5    xxxxxd3432ab   2 weeks ago    106MB
livekit/livekit-server         v1.2.1    xxx2f80af7a8   2 weeks ago    37.8MB
[...]
When you will update traefik I will make new tests and report to you the result.

@duiniuluantanqin Try to downgrade traefik to v2.8.5 and check if livekit is in v1.2.1 in your docker-compose.yaml.

**Comment by duiniuluantanqin** [comment]
@CaosFR Thanks for your answer. but i am not use `traefik`

**Comment by duiniuluantanqin** [comment]
@CaosFR Thanks for your answer. but i am not use `traefik`

**Comment by cnderrauber** [comment]
@CaosFR  @duiniuluantanqin can you try this branch (https://github.com/livekit/livekit/pull/1062) for the fix ?  it should fix your problem with the udp mux issue

**Comment by CaosFR** [comment]
@cnderrauber Thanks for your help, I will try next week and reply here

**Comment by duiniuluantanqin** [comment]
Will `livekit-server` upgrade automatically ? today, it works well with do nothing, just like error occured. it`s amaing.

**Comment by cnderrauber** [comment]
No, livekit-server will not upgrade itself, and #1062 is not merged yet.

**Comment by CaosFR** [comment]
@cnderrauber I try to use your tree but I dont find any repository for my docker-compose.yaml

`image: livekit/livekit-server:v1.2.1`

How can I install your version as a `docker images` ? May I find a ".tar" file somewhere ?

**Comment by cnderrauber** [comment]
@CaosFR This is not released yet so there is no docker image provided.. I have created a new PR for pion/ice https://github.com/pion/ice/pull/483 that should fix your issue cause by latest change, you can try again after it is released

**Comment by cnderrauber** [comment]
Fixed by #1081

**Comment by CaosFR** [comment]
I'm sorry it's not working. The problem still the same after update.

**Comment by davidzhao** [comment]
you are not using automatic IP mapping with `use_external_ip: false`

if that's the case, what is --node-ip being set to? Can you share the ICE candidates while trying to connect to the server? It could be found by going to chrome://webrtc-internals and looking for `remote candidates`

**Comment by CaosFR** [comment]
Thanks for your help. Can you explain me what do you want with chrome://webrtc-internals ? It's for me ou for my client s?
 --node-ip is set to my local IP (192.168.X.X). I dont have a public DNS so they are a NAT forwarding from public IP. The etc/hosts are configure to match the IP with traefik url.

I have made come test :

`-node-ip PUBLIC_IP` and `use_external_ip: true` => Livekit work outside, not LAN
`node-ip PUBLIC_IP` and `use_external_ip: false` => Livekit work outside, not LAN
`node-ip PRIVATE_IP` and `use_external_ip: true` => Livekit work outside, not LAN
`node-ip PRIVATE_IP` and `use_external_ip: false` => Livekit work LAN, not outside

**Comment by cnderrauber** [comment]
@CaosFR you can expand the `ICE candidate grid` in webrtc-internals, it will show you all the local and remote candidates connections. Also, in the event section, you can see the addIceCandidates event, expand it will see the details for that.
Can you get both informations from clients connect to v1.2.1 and latest, and we will see the different cause issue

**Comment by cnderrauber** [comment]
Have setup a AWS/EC2 env, with latest docker image and you docker-compose.yml/livekit.yaml, it works well for internet connect with `node-ip PRIVATE_IP` and `use_external_ip: false`. The selected candidate is srflx and prflx, that is expected as both client/server is under NAT. Wait for your information to verify the issue.

**Comment by CaosFR** [comment]
@cnderrauber Thanks for your help. I'm away from my server for a couples of days. I'm will try your instructions soon I back :) .

**Comment by eIskandarov** [comment]
Hi guys,

we actually have a similar issues in one of our networks.
The fastest way to reproduce that there is just to:

1. Go to https://livekit.io/playground
2. Create a room and run the session
3. Join the same room from the other browser tab

**Result:**

Participants connect to the room, but can't see each other.
After a while both of them disconnect due to an error `could not createOffer with closed peer connection`

It should work still right in that case?
Could you please advice on how to debug any potential peerConnection issues?

Webrtc dump attatched.
[webrtc_internals_dump (1).txt](https://github.com/livekit/livekit/files/9952281/webrtc_internals_dump.1.txt)

Thanks in advance.

**Comment by cnderrauber** [comment]
@eIskandarov Your case is different with this, the playground is using cloud env, from the logs you posted, your client has connected but disconnect after few seconds, maybe caused by poor connection quality to the cloud server. Can you switch to another network connection and try again?
```
    {
     "time": "07/11/2022, 18:16:24",
     "type": "icegatheringstatechange",
     "value": "complete"
    },
    {
     "time": "07/11/2022, 18:16:24",
     "type": "iceconnectionstatechange",
     "value": "connected"
    },
    {
     "time": "07/11/2022, 18:16:24",
     "type": "connectionstatechange",
     "value": "connected"
    },

.....

    {
     "time": "07/11/2022, 18:16:28",
     "type": "iceconnectionstatechange",
     "value": "disconnected"
    },
    {
     "time": "07/11/2022, 18:16:28",
     "type": "connectionstatechange",
     "value": "disconnected"
    },
    {
     "time": "07/11/2022, 18:16:38",
     "type": "connectionstatechange",
     "value": "failed"
    },
```

**Comment by eIskandarov** [comment]
Hi @cnderrauber ,

Yes, In another network it actually works just fine. So it seems to be just a local issue.
Thanks :)

**Comment by burzomir** [comment]
@cnderrauber This issue still exists unfortunately.
We hoped this one may solve it https://github.com/livekit/livekit/issues/1216 but it doesn't do the trick.

The pattern we observe is that a participant connects, publishes tracks but then the connection drops.
The old solution based on Janus works perfectly fine for the same participant.

Here are some logs:

Chrome:
```
