### ISSUE TITLE
loadavg for Windows is not supported

### ISSUE THREAD

**Issue by agoenks29D** [livekit/livekit#1175]
**Describe the bug**

 When i try using egress in local development, i got error message **egress not connected (redis required)**, so i think server didn't connect to redis automatically and then i try to load my own config file, but i got error too. I didn't have any idea to test 

**Server**
- Version: 1.3.1
- Environment: local dev
- config file changed : 
 - `use_extrnal_ip` set to `false`

Screenshot
![image](https://user-images.githubusercontent.com/11814324/202780858-ab3c19ba-0c85-459b-8bcd-bb272d490c30.png)

**Comment by davidzhao** [comment]
can you copy and paste the full logs? it's difficult to read a screenshot.

**Comment by agoenks29D** [comment]
**Command**
```bash
server --dev --config config-development.yml
```

**Output:**
2022-11-19T18:25:42.300+0700    INFO    livekit service/wire_gen.go:186 using multi-node routing via redis      {"sentinel": false, "addr": "localhost:6379"}
2022-11-19T18:25:42.733+0700    DEBUG   livekit routing/redisrouter.go:377      starting redisWorker    {"nodeID": "ND_LIFp2Z23"}
2022-11-19T18:25:43.356+0700    INFO    livekit service/server.go:212   starting LiveKit server {"portHttp": 7880, "nodeID": "ND_LIFp2Z23", "nodeIP": "169.254.7.197", "version": "1.3.1", "rtc.portTCP": 7881, "rtc.portICERange": [50000, 60000]}
2022-11-19T18:25:44.746+0700    ERROR   livekit routing/redisrouter.go:481      could not update node stats     {"error": "loadavg for Windows is not supported"}
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).handleRTCMessage
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:481
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:409
2022-11-19T18:25:44.749+0700    ERROR   livekit routing/redisrouter.go:410      error processing RTC message    {"error": "loadavg for Windows is not supported"}
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:410
2022-11-19T18:25:46.761+0700    ERROR   livekit routing/redisrouter.go:481      could not update node stats     {"error": "loadavg for Windows is not supported"}
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).handleRTCMessage
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:481
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:409
2022-11-19T18:25:46.761+0700    ERROR   livekit routing/redisrouter.go:410      error processing RTC message    {"error": "loadavg for Windows is not supported"}
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:410
2022-11-19T18:25:48.766+0700    ERROR   livekit routing/redisrouter.go:481      could not update node stats     {"error": "loadavg for Windows is not supported"}
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).handleRTCMessage
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:481
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:409
2022-11-19T18:25:48.766+0700    ERROR   livekit routing/redisrouter.go:410      error processing RTC message    {"error": "loadavg for Windows is not supported"}
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.1/pkg/routing/redisrouter.go:410
2022-11-19T18:25:50.285+0700    INFO    livekit server/main.go:249      exit requested, shutting down   {"signal": "interrupt"}
2022-11-19T18:25:50.285+0700    DEBUG   livekit routing/redisrouter.go:302      stopping RedisRouter
2022-11-19T18:25:50.286+0700    DEBUG   livekit routing/redisrouter.go:375      finishing redisWorker   {"nodeID": "ND_LIFp2Z23"}

**Comment by davidzhao** [comment]
I see, we'll fix this one for the next release. sorry about the breakage.

**Comment by davidzhao** [comment]
fixed and released. resolving

**Comment by jmcker** [comment]
I still see this in v1.4.2 while trying to use ingress with Redis.

```
2023-05-23T16:10:20.856-0500    INFO    livekit redis/redis.go:92       connecting to redis     {"simple": true, "addr": "localhost:6379"}
2023-05-23T16:10:21.028-0500    INFO    livekit service/server.go:219   starting LiveKit server {"portHttp": 7880, "nodeID": "ND_Qltc02Qu", "nodeIP": "172.20.160.1", "version": "1.4.2", "bindAddresses": ["0.0.0.0"], "rtc.portTCP": 7881, "rtc.portUDP": 7882}
2023-05-23T16:10:23.027-0500    ERROR   livekit routing/redisrouter.go:538      could not update node stats     {"error": "loadavg for Windows is not supported"}
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).handleRTCMessage
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.4.2/pkg/routing/redisrouter.go:538
github.com/livekit/livekit-server/pkg/routing.(*RedisRouter).redisWorker
        /home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.4.2/pkg/routing/redisrouter.go:460
2023-05-23T16:10:23.027-0500    ERROR   livekit routing/redisrouter.go:461      error processing RTC message    {"error": "loadavg for Windows is not supported"
```
