### ISSUE TITLE
Generator compatibility with podman

### ISSUE THREAD

**Issue by ericnething** [livekit/livekit#570]
I don't understand why issue #539 was closed with no resolution.

**Describe the bug**
When I run the command for step 1 of the installation process, it does not work.

```
docker run --rm -it -v$PWD:/output livekit/generate
```

No files are generated as a result of running this command. Because no configuration file is generated, it is impossible to complete step 1 of the installation process, which means I cannot use this software at all.

The environment varible `PWD` is set correctly. I can replace it with any value, but it makes no difference. 

**Server**
- OS: Linux
- Version: 0.15.5
- Environment: local

**Client**
None

**To Reproduce**
1. run the command in a terminal emulator

**Expected behavior**
I expect that it will do what the installation guide says it will do: generate the configuration files.

**Comment by adarsh-technocrat** [comment]
Hey @ericnething  getting the same issue :(

**Comment by davidzhao** [comment]
@ericnething apologies for misunderstanding in the other thread. I thought you had figured it out by using podman.

I'm not sure why it's not showing up for you. I just created a Linux VM and ran the above successfully. What's the best way for me to reproduce this? How do I replicate your environment?

**Comment by ericnething** [comment]
Run a VM with Fedora or Ubuntu, then install podman (which is the replacement for docker on linux) from the repositories.

**Comment by davidzhao** [comment]
> Run a VM with Fedora or Ubuntu, then install podman (which is the replacement for docker on linux) from the repositories.

We do not support podman at the moment. Can you reproduce with docker?

**Comment by ericnething** [comment]
Docker is not available in the repositories in Fedora, as it has been replaced by podman, which often includes an alias for `docker` to resolve to `podman`. I do not know if it is possible to have both installed. Ubuntu seems to provide a "transitional package" for docker. I tried to figure out how to install docker manually, but apparently I need to create an account on docker hub in order to download the files, or view the installion instructions. Docker seems to go against the ideas of FOSS, which is why I believe there was a replacement created for it.

This is all very complicated just to generate a configuration file. Is there a simpler way to do this?

**Comment by davidzhao** [comment]
That makes sense.. it'd be great to support podman officially. The key issue is being able to write files to the local system, which doesn't appear to be simple to do.

You can definitely just create a config file from scratch instead of using the generator. Here is [an example](https://docs.livekit.io/deploy#configuration) and [full docs](https://github.com/livekit/livekit-server/blob/master/config-sample.yaml) on what the options are.

**Comment by davidzhao** [comment]
A potential fix has been pushed. If anyone with podman could give it another try, that'd be appreciated!

**Comment by davidzhao** [comment]
closing as it's been resolved.

**Comment by apastuszak** [comment]
I'm still having an issue with this. I run the livekit/generate command in podman and no files get written. What was the fix that was pushed @davidzhao
